<?php $this->pageType("gallery-list")?>
<?php $this->breadcrumbs("Gallery", $this->basePath() . "/gallery")?>
<?php $this->headTitle("Gallery")?>
<?php $this->appendCss("/atp-gallery/css/style.less")?>

<div class="gallery" id="gallery-main">
	<h1>Image Gallery</h1>
	<ul class="category-list">
		<?php foreach($categories as $category) { ?>
			<li>
				<div class="gallery-list-item">
					<a href="<?=$this->basePath() . "/gallery/list/" . $category->url?>">
						<img src="<?=$this->basePath() . $this->resize(array(
							'width' => $thumbnailSize,
							'height' => $thumbnailSize,
							'mode' => 'fit',
							'path' => !empty($category->thumbnailFile)
								? $category->filePath("thumbnailFile")
								: \ATPCms\Model\Image::missingImage()->filePath("imageFile")
						))?>" />
						<h3><?=$category->name?></h3>
					</a>
				</div>				
			</li>
		<?php } ?>
	</ul>
</div>