<?php $this->pageType("gallery-list")?>
<?php $this->breadcrumbs($category->name, $this->basePath() . "/gallery/list/" . $category->url)?>
<?php $this->breadcrumbs("Gallery", $this->basePath() . "/gallery")?>
<?php $this->headTitle($category->name)?>
<?php $this->headTitle("Gallery")?>
<?php $this->appendCss("/atp-gallery/css/style.less")?>

<div class="gallery" id="gallery-<?=$category->url?>">
	<h1><?=$category->name?> Gallery</h1>
	<ul class="image-list">
		<?php foreach($images as $image) { ?>
			<li>
				<div class="gallery-list-item">
					<a href="<?=$this->basePath() . "/gallery/view/" . $image->url?>">
						<img src="<?=$this->basePath() . $this->resize(array(
							'width' => $thumbnailSize,
							'height' => $thumbnailSize,
							'mode' => 'crop',
							'path' => !empty($image->thumbnailFile)
								? $image->filePath("thumbnailFile")
								: $image->filePath("imageFile")
						))?>" />
					</a>
					<h3><?=$image->title?></h3>
				</div>				
			</li>
		<?php } ?>
	</ul>
</div>