<?php $this->pageType("gallery-list")?>
<?php $this->breadcrumbs("Gallery", $this->basePath() . "/gallery")?>
<?php $this->headTitle("Gallery")?>

<div class="gallery">
	<ul class="image-list">
		<?php foreach($images as $image) { ?>
			<li>
				<a href="<?=$this->basePath() . "/gallery/view/" . $image->url?>">
					<img src="<?=$this->basePath() . $this->resize(array(
						'width' => 200,
						'height' => 200,
						'mode' => 'fit',
						'path' => $image->filePath("thumbnail")
					))?>" />
				</a>
				<h3><?=$image->title?></h3>
				
			</li>
		<?php } ?>
	</ul>
</div>