<?php $this->pageType("gallery-view")?>
<?php $this->breadcrumbs($image->title, $this->basePath() . "/gallery/view/" . $image->url)?>
<?php $this->breadcrumbs("Gallery", $this->basePath() . "/gallery")?>
<?php $this->headTitle($image->title)?>
<?php $this->headTitle("Gallery")?>

<div class="gallery-view">
	<div class="gallery-image">
		<span>
			<img src="<?=$this->basePath() . $image->filePath('imageFile')?>" />
			<h1><?=$image->title?></h1>
		</span>
	</div>
</div>