<?php $this->pageType("gallery-view")?>
<?php $this->breadcrumbs($image->title, $this->basePath() . "/gallery/view/" . $image->url)?>
<?php $this->breadcrumbs("Gallery", $this->basePath() . "/gallery")?>
<?php $this->headTitle($image->title)?>
<?php $this->headTitle("Gallery")?>
<?php $this->appendCss("/atp-gallery/css/style.less")?>

<div class="gallery-view">
	<div class="gallery-image">
		<h1><?=$image->title?></h1>
		<span>
			<img src="<?=$this->basePath() . $image->filePath('imageFile')?>" />
		</span>
	</div>
</div>